apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-panel
  namespace: argocd
spec:
  source:
    path: argocd/components/argocd-panel
    repoURL: https://github.com/bernatvadell/k8s-formacion.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true